In [1]:
import pandas as pd

In [2]:
winequality_red = pd.read_csv("http://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv",delimiter=";")

In [3]:
winequality_red.describe()

fixed acidity  volatile acidity  citric acid  residual sugar  \
count    1599.000000       1599.000000  1599.000000     1599.000000   
mean        8.319637          0.527821     0.270976        2.538806   
std         1.741096          0.179060     0.194801        1.409928   
min         4.600000          0.120000     0.000000        0.900000   
25%         7.100000          0.390000     0.090000        1.900000   
50%         7.900000          0.520000     0.260000        2.200000   
75%         9.200000          0.640000     0.420000        2.600000   
max        15.900000          1.580000     1.000000       15.500000   

         chlorides  free sulfur dioxide  total sulfur dioxide      density  \
count  1599.000000          1599.000000           1599.000000  1599.000000   
mean      0.087467            15.874922             46.467792     0.996747   
std       0.047065            10.460157             32.895324     0.001887   
min       0.012000             1.000000              6.000000     0.990070   
25%       0.070000             7.000000             22.000000     0.995600   
50%       0.079000            14.000000             38.000000     0.996750   
75%       0.090000            21.000000             62.000000     0.997835   
max       0.611000            72.000000            289.000000     1.003690   

                pH    sulphates      alcohol      quality  
count  1599.000000  1599.000000  1599.000000  1599.000000  
mean      3.311113     0.658149    10.422983     5.636023  
std       0.154386     0.169507     1.065668     0.807569  
min       2.740000     0.330000     8.400000     3.000000  
25%       3.210000     0.550000     9.500000     5.000000  
50%       3.310000     0.620000    10.200000     6.000000  
75%       3.400000     0.730000    11.100000     6.000000  
max       4.010000     2.000000    14.900000     8.000000

In [4]:
winequality_white = pd.read_csv("http://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-white.csv",delimiter=";")

In [5]:
winequality_white.describe()

fixed acidity  volatile acidity  citric acid  residual sugar  \
count    4898.000000       4898.000000  4898.000000     4898.000000   
mean        6.854788          0.278241     0.334192        6.391415   
std         0.843868          0.100795     0.121020        5.072058   
min         3.800000          0.080000     0.000000        0.600000   
25%         6.300000          0.210000     0.270000        1.700000   
50%         6.800000          0.260000     0.320000        5.200000   
75%         7.300000          0.320000     0.390000        9.900000   
max        14.200000          1.100000     1.660000       65.800000   

         chlorides  free sulfur dioxide  total sulfur dioxide      density  \
count  4898.000000          4898.000000           4898.000000  4898.000000   
mean      0.045772            35.308085            138.360657     0.994027   
std       0.021848            17.007137             42.498065     0.002991   
min       0.009000             2.000000              9.000000     0.987110   
25%       0.036000            23.000000            108.000000     0.991723   
50%       0.043000            34.000000            134.000000     0.993740   
75%       0.050000            46.000000            167.000000     0.996100   
max       0.346000           289.000000            440.000000     1.038980   

                pH    sulphates      alcohol      quality  
count  4898.000000  4898.000000  4898.000000  4898.000000  
mean      3.188267     0.489847    10.514267     5.877909  
std       0.151001     0.114126     1.230621     0.885639  
min       2.720000     0.220000     8.000000     3.000000  
25%       3.090000     0.410000     9.500000     5.000000  
50%       3.180000     0.470000    10.400000     6.000000  
75%       3.280000     0.550000    11.400000     6.000000  
max       3.820000     1.080000    14.200000     9.000000

In [6]:
winequality_red['label'] = [0]*1599
winequality_white['label'] = [1]*4898

In [7]:
alldata = winequality_red.append(winequality_white)

In [8]:
alldata.describe()

fixed acidity  volatile acidity  citric acid  residual sugar  \
count    6497.000000       6497.000000  6497.000000     6497.000000   
mean        7.215307          0.339666     0.318633        5.443235   
std         1.296434          0.164636     0.145318        4.757804   
min         3.800000          0.080000     0.000000        0.600000   
25%         6.400000          0.230000     0.250000        1.800000   
50%         7.000000          0.290000     0.310000        3.000000   
75%         7.700000          0.400000     0.390000        8.100000   
max        15.900000          1.580000     1.660000       65.800000   

         chlorides  free sulfur dioxide  total sulfur dioxide      density  \
count  6497.000000          6497.000000           6497.000000  6497.000000   
mean      0.056034            30.525319            115.744574     0.994697   
std       0.035034            17.749400             56.521855     0.002999   
min       0.009000             1.000000              6.000000     0.987110   
25%       0.038000            17.000000             77.000000     0.992340   
50%       0.047000            29.000000            118.000000     0.994890   
75%       0.065000            41.000000            156.000000     0.996990   
max       0.611000           289.000000            440.000000     1.038980   

                pH    sulphates      alcohol      quality        label  
count  6497.000000  6497.000000  6497.000000  6497.000000  6497.000000  
mean      3.218501     0.531268    10.491801     5.818378     0.753886  
std       0.160787     0.148806     1.192712     0.873255     0.430779  
min       2.720000     0.220000     8.000000     3.000000     0.000000  
25%       3.110000     0.430000     9.500000     5.000000     1.000000  
50%       3.210000     0.510000    10.300000     6.000000     1.000000  
75%       3.320000     0.600000    11.300000     6.000000     1.000000  
max       4.010000     2.000000    14.900000     9.000000     1.000000

In [9]:
alldata.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  label  
0      9.4        5      0  
1      9.8        5      0  
2      9.8        5      0  
3      9.8        6      0  
4      9.4        5      0

# Data Preprocessing

In [10]:
x_columns = alldata.columns[:-1]

In [11]:
X = alldata.values[:,:-1]

In [12]:
X

array([[  7.4 ,   0.7 ,   0.  , ...,   0.56,   9.4 ,   5.  ],
       [  7.8 ,   0.88,   0.  , ...,   0.68,   9.8 ,   5.  ],
       [  7.8 ,   0.76,   0.04, ...,   0.65,   9.8 ,   5.  ],
       ..., 
       [  6.5 ,   0.24,   0.19, ...,   0.46,   9.4 ,   6.  ],
       [  5.5 ,   0.29,   0.3 , ...,   0.38,  12.8 ,   7.  ],
       [  6.  ,   0.21,   0.38, ...,   0.32,  11.8 ,   6.  ]])

In [13]:
Y = alldata.values[:,-1]

In [14]:
Y

array([ 0.,  0.,  0., ...,  1.,  1.,  1.])

# Split Data to training set and testing set

In [15]:
from sklearn import preprocessing

In [16]:
# ?preprocessing.StandardScaler

In [17]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X, Y, test_size=0.25, random_state=42)

# Do Normalization

In [18]:
from sklearn.preprocessing import StandardScaler
stds = StandardScaler()
X_train_scaled = stds.fit_transform(X_train)
X_test_scaled = stds.transform(X_test)

In [21]:
from sklearn import metrics

# LogisticRegression

In [22]:
from sklearn.linear_model import LogisticRegression
clf_l2_LR = LogisticRegression(C=0.1, penalty='l1', tol=0.01,verbose=2)


In [23]:
clf_l2_LR.fit(X_train_scaled,y_train)

[LibLinear]

LogisticRegression(C=0.1, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l1', random_state=None, solver='liblinear', tol=0.01,
          verbose=2, warm_start=False)

In [24]:
predict_y = clf_l2_LR.predict(X_test_scaled)

In [25]:
print("accuracy_score",metrics.accuracy_score(y_test,predict_y))
print("f1_score",metrics.f1_score(y_test,predict_y,average='micro'))

accuracy_score 0.989538461538
f1_score 0.989538461538


In [26]:

for cname,coef in zip(x_columns.tolist(),clf_l2_LR.coef_.tolist()[0]):
    print(cname,"\t\t",coef)

fixed acidity 		 -0.7436818644365313
volatile acidity 		 -1.2807253452116418
citric acid 		 0.06113968611818141
residual sugar 		 1.1143977560663392
chlorides 		 -0.6834845551384324
free sulfur dioxide 		 -0.32425790339382504
total sulfur dioxide 		 2.5132825163659027
density 		 -1.3634678276932073
pH 		 -0.6448726076002574
sulphates 		 -0.7555581261556914
alcohol 		 -0.009480890914708056
quality 		 -0.09294275323016071


# SGDClassifier

In [27]:
from sklearn.linear_model import SGDClassifier

clf = SGDClassifier(loss="log", penalty="l1",max_iter=2000,alpha=0.000001)
clf.fit(X_train_scaled,y_train)

predict_y = clf.predict(X_test_scaled)

In [28]:
print("accuracy_score",metrics.accuracy_score(y_test,predict_y))
print("f1_score",metrics.f1_score(y_test,predict_y,average='micro'))

accuracy_score 0.990153846154
f1_score 0.990153846154


In [29]:
for cname,coef in zip(x_columns.tolist(),clf.coef_.tolist()[0]):
    print(cname,"\t\t",coef)

fixed acidity 		 -0.23889124378825696
volatile acidity 		 -1.5974360097796763
citric acid 		 0.2949555475399215
residual sugar 		 5.406508762152413
chlorides 		 -0.9801964861802112
free sulfur dioxide 		 -1.322890534123144
total sulfur dioxide 		 3.2203218148170243
density 		 -4.8507311152785215
pH 		 0.0
sulphates 		 -0.6339452972581275
alcohol 		 -1.423607645846471
quality 		 -0.24162191856380774


# 預測 Quality

In [30]:
alldata.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  label  
0      9.4        5      0  
1      9.8        5      0  
2      9.8        5      0  
3      9.8        6      0  
4      9.4        5      0

In [31]:
X_train_q = X_train_scaled[:,:-1]

In [32]:
X_test_q = X_test_scaled[:,:-1]

In [33]:
X_train_scaled

array([[  2.11284802e-03,   3.32462696e-01,  -1.83218163e-03, ...,
          1.68873481e+00,  -4.94217715e-01,  -9.37018306e-01],
       [  2.79891768e+00,   8.27735349e-01,   7.59332762e-01, ...,
          1.55351390e+00,   2.59076212e-01,   2.03414666e-01],
       [  8.56692104e-01,   1.69446249e+00,  -1.40225808e-01, ...,
          5.39357112e-01,  -2.43119739e-01,   2.03414666e-01],
       ..., 
       [ -6.19399338e-01,   2.08644533e-01,  -8.32193938e-01, ...,
         -6.77631034e-01,  -8.29015016e-01,  -9.37018306e-01],
       [ -5.41710315e-01,  -4.72355364e-01,   1.24371045e+00, ...,
         -4.07189224e-01,  -8.29015016e-01,  -9.37018306e-01],
       [  2.11284802e-03,   1.75637157e+00,  -1.80094932e+00, ...,
          6.60839440e-02,  -8.29015016e-01,  -9.37018306e-01]])

In [34]:
y_train_q = X_train_scaled[:,-1]

In [35]:
y_test_q = X_test_scaled[:,-1]

In [36]:
from sklearn.linear_model import LinearRegression,SGDRegressor
lr = SGDRegressor(loss='squared_loss', 
                  penalty='l2', alpha=0.0001, l1_ratio=0.15, 
                  fit_intercept=True, max_iter=None, tol=None, 
                  shuffle=True, verbose=0, epsilon=0.1, random_state=None, learning_rate='invscaling', 
                  eta0=0.01, power_t=0.25, warm_start=False, average=False, n_iter=None)

In [37]:
lr.fit(X_train_q,y_train_q)

/usr/local/lib/python3.6/site-packages/sklearn/linear_model/stochastic_gradient.py:128: FutureWarning: max_iter and tol parameters have been added in <class 'sklearn.linear_model.stochastic_gradient.SGDRegressor'> in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  "and default tol will be 1e-3." % type(self), FutureWarning)


SGDRegressor(alpha=0.0001, average=False, epsilon=0.1, eta0=0.01,
       fit_intercept=True, l1_ratio=0.15, learning_rate='invscaling',
       loss='squared_loss', max_iter=None, n_iter=None, penalty='l2',
       power_t=0.25, random_state=None, shuffle=True, tol=None, verbose=0,
       warm_start=False)

In [38]:
# 拿 training 直接驗證
predict_y = lr.predict(X_train_q)
metrics.mean_absolute_error(y_train_q,predict_y)

0.64908043754476508

In [39]:
# 拿 testing data 作驗證
predict_y = lr.predict(X_test_q)
metrics.mean_absolute_error(y_test_q,predict_y)

0.65271848941174171

In [40]:
# 還原成原始資料 作驗證
test_result = stds.inverse_transform(np.column_stack((X_test_q, predict_y)))
metrics.mean_absolute_error(test_result[:,-1],X_test[:,-1])

0.57234270250764452