# Linear Regression have two methodolgy to solve this problem
* Normal Equation
* Gradient Descent (ToDo)


In [ ]:
from sklearn import metrics
import numpy as np


In [15]:
from sklearn.datasets import load_boston
X, y = load_boston(return_X_y=True)
print(X.shape)
print(y.shape)

(506, 13)
(506,)


# Normal Equation(do it by native numpy code)
<img width=20% src="https://i.imgur.com/aZuHRKU.png" />
* the objective is to minimize the below square error
<img width=20% src="https://i.imgur.com/uuj1z1y.jpg" />
* x 為 training data as m*n matrix , m is the numboer of sample . n is the number of feature size.
* user above function could find the best parameter theta, it could minimize the squre error. 
* so this method is called as "Least Squares"

In [17]:
theta = np.linalg.inv((X.T).dot(X)).dot(X.T).dot(y)

In [44]:
theta

array([-9.28965170e-02,  4.87149552e-02, -4.05997958e-03,  2.85399882e+00,
       -2.86843637e+00,  5.92814778e+00, -7.26933458e-03, -9.68514157e-01,
        1.71151128e-01, -9.39621540e-03, -3.92190926e-01,  1.49056102e-02,
       -4.16304471e-01])

In [27]:
def linear_regression(input_X):
    return input_X.dot(theta)
    

In [48]:
predict_y = linear_regression(X)

In [59]:
theta0 = (predict_y-y)
theta0.mean()

-2.5276223801742696e-16

In [49]:
metrics.mean_squared_error(y,predict_y)

24.166099330126492

In [50]:
metrics.mean_absolute_error(y,predict_y)

3.2867335789615058

# Scikit Learn 內建的方法
* 請參考 [sklearn](https://github.com/scikit-learn/scikit-learn/blob/95119c13a/sklearn/linear_model/_base.py#L391) 裡面的程式碼
* 請參考 [scipy](https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.nnls.html)

In [51]:
from sklearn.linear_model import LinearRegression

reg = LinearRegression().fit(X, y)


In [52]:
predict_y = reg.predict(X)

In [53]:
metrics.mean_squared_error(y,predict_y)

21.894831181729202

In [39]:
metrics.mean_absolute_error(y,predict_y)

3.270862810900316

# Compare Theta

In [46]:
theta

array([-9.28965170e-02,  4.87149552e-02, -4.05997958e-03,  2.85399882e+00,
       -2.86843637e+00,  5.92814778e+00, -7.26933458e-03, -9.68514157e-01,
        1.71151128e-01, -9.39621540e-03, -3.92190926e-01,  1.49056102e-02,
       -4.16304471e-01])

In [45]:
reg.coef_

array([-1.08011358e-01,  4.64204584e-02,  2.05586264e-02,  2.68673382e+00,
       -1.77666112e+01,  3.80986521e+00,  6.92224640e-04, -1.47556685e+00,
        3.06049479e-01, -1.23345939e-02, -9.52747232e-01,  9.31168327e-03,
       -5.24758378e-01])

In [60]:
reg.intercept_

36.459488385090125