# LSTM Esentail 
<img src="https://i.imgur.com/DwVvNgG.png" />

## 最單純的 LSTM
* [參考資料為](https://machinelearningmastery.com/return-sequences-and-return-states-for-lstms-in-keras/)
* cell 只有一個
* 為兩筆資料分別為 [0.1, 0.2, 0.3] 及 [0.3, 0.2, 0.1]
* 故需 Reshape 為 (batch_size,step_size,feature_dim) => (2,3,1)
* 下面的範例出輸為 batch_size*cell_size

In [92]:
from keras.models import Model
from keras.layers import Input
from keras.layers import LSTM
from numpy import array
# define model
inputs1 = Input(shape=(3, 1))
lstm1 = LSTM(1)(inputs1)
model = Model(inputs=inputs1, outputs=lstm1)
# define input data
data = array([[0.1, 0.2, 0.3],[0.3, 0.2, 0.1]],).reshape((2,3,1))
# make and show prediction
print(model.predict(data))

[[-0.11857762]
 [-0.08272369]]


## 10 個 Cell 的情況

In [93]:
from keras.models import Model
from keras.layers import Input
from keras.layers import LSTM
from numpy import array
# define model
inputs1 = Input(shape=(3, 1))
lstm1 = LSTM(1)(inputs1)
model = Model(inputs=inputs1, outputs=lstm1)
# define input data
data = array([[0.1, 0.2, 0.3],[0.3, 0.2, 0.1]],).reshape((2,3,1))
# make and show prediction
print(model.predict(data))

[[ 0.07128293]
 [ 0.05044615]]


## Return Sequnce
* 有時候我們會需要知道每一個 Step 的反應值，例如 Attention Model 就會需要了
* 每一筆 Row 都總共有三個 Step ，故從一筆變成三筆資料
* 故回傳的資料為 $row_count*step_size*output_dim = 2*3*5 $

In [141]:
from keras.models import Model
from keras.layers import Input
from keras.layers import LSTM
from numpy import array
# define model
inputs1 = Input(shape=(3, 1))
lstm1 = LSTM(5,return_sequences=True)(inputs1)
model = Model(inputs=inputs1, outputs=lstm1)
# define input data
data = array([[0.1, 0.2, 0.3],[0.3, 0.2, 0.1]],).reshape((2,3,1))
# make and show prediction
print(model.predict(data))

[[[-0.00571752 -0.01071675 -0.00832335  0.01219951 -0.0038277 ]
  [-0.01348902 -0.02929329 -0.02051001  0.03178019 -0.01143293]
  [-0.02144734 -0.0528556  -0.03429443  0.05571545 -0.02219554]]

 [[-0.01725512 -0.03203397 -0.02506758  0.0365537  -0.01092883]
  [-0.017811   -0.04451959 -0.02757261  0.04670093 -0.01896706]
  [-0.01126208 -0.04223189 -0.01959449  0.04138551 -0.02205685]]]


## Return Hidden Status  
* Step_Size = 3
* Feature_Dim =4
* LSTM Cell_Size = 5 => output_feature= 5

In [132]:
from keras.models import Model
from keras.layers import Input
from keras.layers import LSTM
from numpy import array
# define model : step_size=3 , feature_dim = 4
inputs1 = Input(shape=(3, 4))
lstm1, state_h, state_c = LSTM(5, return_state=True)(inputs1)
model = Model(inputs=inputs1, outputs=[lstm1, state_h, state_c])
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_46 (InputLayer)        (None, 3, 4)              0         
_________________________________________________________________
lstm_64 (LSTM)               [(None, 5), (None, 5), (N 200       
Total params: 200
Trainable params: 200
Non-trainable params: 0
_________________________________________________________________


In [135]:
# define input data : two rows !!!
data = np.random.rand(2,3,4)
 

In [136]:
# make and show prediction
result,h,c = model.predict(data)
print(result)
print('')
print(h)
print('')
print(c)

[[ 0.11021777  0.03445232  0.07700986 -0.1312259   0.06634397]
 [ 0.0330804   0.10099667  0.10058533 -0.04455258  0.01756349]]

[[ 0.11021777  0.03445232  0.07700986 -0.1312259   0.06634397]
 [ 0.0330804   0.10099667  0.10058533 -0.04455258  0.01756349]]

[[ 0.25357416  0.09389415  0.17182902 -0.23218882  0.11518192]
 [ 0.06789154  0.230139    0.21743184 -0.0778769   0.03369107]]


## Return State and Sequnce

In [142]:
from keras.models import Model
from keras.layers import Input
from keras.layers import LSTM
from numpy import array
# define model : step_size=3 , feature_dim = 4
inputs1 = Input(shape=(3, 4))
lstm1, state_h, state_c = LSTM(5, return_state=True,return_sequences=True)(inputs1)
model = Model(inputs=inputs1, outputs=[lstm1, state_h, state_c])
model.summary()

# define input data : two rows !!!
data = np.random.rand(2,3,4)


# make and show prediction
result,h,c = model.predict(data)

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_52 (InputLayer)        (None, 3, 4)              0         
_________________________________________________________________
lstm_69 (LSTM)               [(None, 3, 5), (None, 5), 200       
Total params: 200
Trainable params: 200
Non-trainable params: 0
_________________________________________________________________


### Result Dim = $row__count*step__size*output__dim=2*3*5$

In [151]:
print(result)

[[[-0.11293191 -0.2143995  -0.0339875   0.14321022  0.08661234]
  [-0.1561099  -0.27486107 -0.04737563  0.24274863  0.15393023]
  [-0.17066154 -0.27306929 -0.0563515   0.21435302  0.15645497]]

 [[-0.12975837 -0.13139297  0.016354    0.12212893  0.09127233]
  [-0.18707757 -0.28833199 -0.01606969  0.22777481  0.12801695]
  [-0.21214634 -0.27837792 -0.03663032  0.23615576  0.20373756]]]


### Hidden Output Dim = $row__count*output_dim$
* 可以看得出來 Result 的每一個 Row 當中的最後一個 Step 的 Ouput 及為 h

In [154]:
print(h)

[[-0.17066154 -0.27306929 -0.0563515   0.21435302  0.15645497]
 [-0.21214634 -0.27837792 -0.03663032  0.23615576  0.20373756]]


### Sate Dim = $row__count*output_dim$

In [155]:
print(c)

[[-0.3449741  -0.69952059 -0.10459338  0.42986715  0.37107053]
 [-0.43414831 -0.65018016 -0.06691437  0.60401654  0.42403555]]
