# Covariance
* 公式 : $\frac {\sum_{i=1}^{n} (x- \bar  X_i)(y- \bar  Y_i)} {N-1}$

相關應該是統計分析中很常見的概念
對於兩個不同的連續變項而言
所謂相關簡單講
就是兩個變項的線性變化
是不是其中一個增加、另一個也會增加？
比方身高高的人往往體重多半也會比較容易重一些
或者其中一個增加、另一個反隨之減少？


想知道的是：有沒有辦法用較簡單的統計方式來描述兩個變項之間的關係？
畢竟一大堆資料沒辦法隨身帶著走
要形容手上的資料的關係
當然是能夠越簡單明瞭越好

而要用來描述兩個變數之間線性相關性的就是「相關係數」(Correlation Coefficient)
相關係數概念的出發點
就是要想辦法用一個數來表示(1)到底兩者之間影響大不大(2)影響的方向(一起變大或反之)
所以希望找的就是兩個隨機變數之間是不是有什麼關聯
這就想到了「共變異數」(Covariance)

 

共變異數的作用就是要知道兩個變數一同變大/變小的程度
想知道如果A變數離均值越遠、B是否也離均值越遠
(A越正B就越正、或A越正B就越負)



In [7]:
import numpy as np
def cov(a, b):

    if len(a) != len(b):
        return

    a_mean = np.mean(a)
    b_mean = np.mean(b)

    sum = 0

    for i in range(0, len(a)):
        sum += ((a[i] - a_mean) * (b[i] - b_mean))

    return sum/(len(a)-1)

In [11]:
feature1 = [1,2,3,4,5]
feature2 = [2,4,6,8,10]
feature3 = [1,0,1,1,1]

In [12]:
print("feature1,feature2:",cov(feature1,feature2))
print("feature1,feature3:",cov(feature1,feature3))
print("feature2,feature3:",cov(feature2,feature3))


feature1,feature2: 5.0
feature1,feature3: 0.25
feature2,feature3: 0.5


In [13]:
m = np.array([feature1,feature2,feature3])
m

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 1,  0,  1,  1,  1]])

In [16]:
# 進行轉置後，每一筆 row 可以視為一筆資料
m.T

array([[ 1,  2,  1],
       [ 2,  4,  0],
       [ 3,  6,  1],
       [ 4,  8,  1],
       [ 5, 10,  1]])

In [14]:
np.cov(m)

array([[  2.5 ,   5.  ,   0.25],
       [  5.  ,  10.  ,   0.5 ],
       [  0.25,   0.5 ,   0.2 ]])